# Generated by Django 4.1.1 on 2022-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Hollywood'), (2, 'Bollywood'), (3, 'Nollywood'), (4, 'K-drama'), (5, 'Tv-series')]),
        ),
    ]
