# Generated by Django 4.1.1 on 2022-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pinterest_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
